# Generated by Django 5.0.1 on 2024-02-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libro', models.CharField(max_length=15)),
                ('pagina', models.CharField(max_length=20)),
            ],
        ),
    ]
