# Generated by Django 5.0.1 on 2024-02-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuario',
            new_name='libro',
        ),
    ]
